### ISSUE TITLE
No trailing newlines in generated code

### ISSUE THREAD

**Issue by shlevy** [google/proto-lens#101]

**Comment by judah** [comment]
Can you be more specific about this request?  It looks like currently the generated files don't have trailing newlines.  Can you explain what difference this formatting change would make?

**Comment by shlevy** [comment]
Ah, sorry, this was a really poor description :grinning: The lack of trailing newlines is IMO a bug (see https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline for the philosophical reasons, but the pragmatic ones are that tools expect it and complain in various ways without it). Concretely: There should be a `\n` at the end of every generated file.

**Comment by judah** [comment]
Sounds reasonable.  Would you like to send a patch?  This is where we create the file contents:
https://github.com/google/proto-lens/blob/master/proto-lens-protoc/src/protoc-gen-haskell.hs#L84

Out of curiosity, which tool complained about the missing newline?  Was it a text editor or something more automated?

**Comment by shlevy** [comment]
`git diff` shows `\ No newline at end of file` and on github there's a red octicon-no-newline (https://octicons.github.com/icon/no-newline/) in the diffs, is how I saw this one. 

Will whip up a patch, thanks!

**Comment by shlevy** [comment]
Sorry, I haven't had time to work on this and won't likely for the forseable future.
