### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by gremdrus** [google/proto-lens#120]
Hello,

I was trying to build this with `stack install` and got this error:

> --  Dumping log file due to warnings: /home/g/src/haskell/proto-lens/.stack-work/logs/proto-lens-protobuf-types-0.2.2.0.log
> 
> [1 of 2] Compiling Main             ( /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/Setup.hs, /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/Main.o )
> [2 of 2] Compiling StackSetupShim   ( /home/g/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/StackSetupShim.o )
> Linking /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/setup ...
> Configuring proto-lens-protobuf-types-0.2.2.0...
> proto-src: warning: directory does not exist.
> **proto-src/google/protobuf/any.proto: No such file or directory**
> callProcess: /usr/local/bin/protoc
> "--plugin=protoc-gen-haskell=/home/g/src/haskell/proto-lens/.stack-work/install/x86_64-linux-nopie/lts-9.0/8.0.2/bin/proto-lens-protoc"
> "--haskell_out=.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/autogen"
> "--proto_path=proto-src" "proto-src/google/protobuf/any.proto"
> "proto-src/google/protobuf/duration.proto"
> "proto-src/google/protobuf/wrappers.proto" (exit 1): failed
>                
> --  End of log file: /home/g/src/haskell/proto-lens/.stack-work/logs/proto-lens-protobuf-types-0.2.2.0.log
> 
> Log files have been written to: /home/g/src/haskell/proto-lens/.stack-work/logs/
> Progress: 33/36
> --  While building package proto-lens-protobuf-types-0.2.2.0 using:
>       /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0 build lib:proto-lens-protobuf-types --ghc-options " -ddump-hi -ddump-to-file"
>     Process exited with code: ExitFailure 1
>     Logs have been written to: /home/g/src/haskell/proto-lens/.stack-work/logs/proto-lens-protobuf-types-0.2.2.0.log
> 
>     [1 of 2] Compiling Main             ( /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/Setup.hs, /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/Main.o )
>     [2 of 2] Compiling StackSetupShim   ( /home/g/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/StackSetupShim.o )
>     Linking /home/g/src/haskell/proto-lens/proto-lens-protobuf-types/.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/setup/setup ...
>     Configuring proto-lens-protobuf-types-0.2.2.0...
>     proto-src: warning: directory does not exist.
>     proto-src/google/protobuf/any.proto: No such file or directory
>     callProcess: /usr/local/bin/protoc
>     "--plugin=protoc-gen-haskell=/home/g/src/haskell/proto-lens/.stack-work/install/x86_64-linux-nopie/lts-9.0/8.0.2/bin/proto-lens-protoc"
>     "--haskell_out=.stack-work/dist/x86_64-linux-nopie/Cabal-1.24.2.0/build/autogen"
>     "--proto_path=proto-src" "proto-src/google/protobuf/any.proto"
>     "proto-src/google/protobuf/duration.proto"
>     "proto-src/google/protobuf/wrappers.proto" (exit 1): failed
> 

Apparently it is looking for `proto-src/google/protobuf/any.proto` and that might be causing the issue?

**Comment by judah** [comment]
Thanks for the report.  You're building from this git repo directly, right?  You'll need to run `git submodule --update --init` to get those files.

I'll update the README to call out that step.

**Comment by gremdrus** [comment]
That was indeed the issue! Thank you so much @judah.
