### ISSUE TITLE
Handle non-capitalized enum values

### ISSUE THREAD

**Issue by lucasdicioccio** [google/proto-lens#152]
Hi, thanks for `proto-lens`; I got it to work on a gRPC client project with somewhat complicated `.proto`s. While making it work, I had to patch a workaround to support valid Enum definitions which do not implement the [recommended style-guide](https://developers.google.com/protocol-buffers/docs/style) and use lower-cased enum value names.

My workaround is to call `toUpper` on enum names. This solution is not really great so I wanted to discuss with you the best implementation choices before making a proper pull request. You can find my patches at:
https://github.com/google/proto-lens/compare/master...lucasdicioccio:workarounds .

**Comment by judah** [comment]
Hi, thank you for reporting this issue.  Fixing names in that case does makes sense.  My only suggesting is to act a little more conservatively and only upper-case the first character (similar to what we do for message names), using `hsName`/`capitalize` from here: https://github.com/google/proto-lens/blob/b342f24e6366474434a48f9510ea42f1bc46d64f/proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs#L343

Does that sound reasonable, and if so, would you like to send a PR?

**Comment by gvd** [comment]
This is definitely a need. This bug can prevent one from communicating with existing services that happen to use enums with lower-case letters.
