### ISSUE TITLE
Open source the gRPC bindings

### ISSUE THREAD

**Issue by isovector** [google/proto-lens#179]
Hey dudes!

Is it possible to open source the gRPC bindings (documented [here](http://reasonablypolymorphic.com/blog/type-directed-code-generation))? I know a few people who are hoping to use it, and it seems better to have one canonical implementation rather than have everyone reimplement it from the blog post.

Much love! Hope you're well!

**Comment by blackgnezdo** [comment]
@isovector, not sure what you are asking. Whether or not google/proto-lens is a good place to host this code? Or something else? I imagine you can chat with @judah about it. IMHO, a separate package here would be fine.

**Comment by isovector** [comment]
@judah, @cem3394 any word on this?

**Comment by lucasdicioccio** [comment]
@isovector FYI I've been implementing a native client/server on top of http2-client/warp and proto-lens.

you may find some interest in the following
- https://github.com/lucasdicioccio/http2-client-grpc (on Hackage already)
- https://github.com/lucasdicioccio/warp-grpc (waiting for an upstream release of my warp patch for some HTTP2 corner-case)

contributions are welcome

**Comment by thumphries** [comment]
The code in question has finally been released. https://github.com/formationai/proto-lens-grpc

This issue can be closed.

I think the next step is to get it (or something derived from it) into proto-lens proper.

**Comment by isovector** [comment]
<3 thanks tim!

**Comment by isovector** [comment]
I'll update my blog post pointing to this repo!
