### ISSUE TITLE
Define our own "def" rather than the one from data-default-class

### ISSUE THREAD

**Issue by judah** [google/proto-lens#194]
The `data-default-class` package is...somewhat controversial.  The main criticism is that `def` doesn't satisfy any laws, so tends to be abused.  See for example the following haskell-cafe thread: https://mail.haskell.org/pipermail/haskell-cafe/2018-May/129053.html

Indeed, from our experience using `proto-lens` on a larger team, we've found that `data-default` creeps into places it's not really intended for; e.g., using it for an integer value instead of an explicit `0`.

However, for protobufs we *do* have a useful law, namely, `encodeMessage def == ""`.

Note that the `proto-lens` library already reexports `def` directly: (`Data.ProtoLens.Message` and `Data.ProtoLens`)

I propose the following changes:

- Remove all our dependencies on `data-default-class` (and `data-default`)
- Change the `Message` class to define its own method `def`:

      class Message m where
          ...
          def :: m

Note that this is a breaking change, so it would cause a major version bump (i.e., `proto-lens-0.4`).  Given that we just released `0.3` which has a fair bit of API churn, I'd probably rather wait a bit before doing another round.  However, it should be fairly easy to write user code that's compatible with both versions, by writing `import Data.ProtoLens (def)`.

**Comment by blackgnezdo** [comment]
If we are rolling our own, does it make sense to name it something else too? Maybe `emptyMessage` (contract to taste)? Transition can be arranged for with a wrapper module setting `def = emptyMessage`. 

It may also be better to do two breaking releases back-to-back in hope that some people will have skipped the .3 release?

**Comment by mitchellwrosen** [comment]
Just chiming in here, `def` _is_ a useful concept for default options, etc. Problem is the `data-default-class` version has shit the bed with all kinds of crazy instances. Perhaps we should try to get a major version bump into it that removes basically all its instances, leaving only derived ones like `(Default a, Default b) => Default (a, b)`. If that happens, then we can go back to all sharing the one class, instead of reinventing it everywhere :)
