### ISSUE TITLE
pretty-print DescriptorProto to *.proto

### ISSUE THREAD

**Issue by joshsh** [google/proto-lens#205]
My use case requires a library to serialize a `DescriptorProto` as a `*.proto` file using proto3 syntax. Has this been considered in proto-lens?

Note similar tickets in the [protocol-buffers](https://github.com/k-bx/protocol-buffers/issues/70) and [proto3-suite](https://github.com/awakesecurity/proto3-suite/issues/75) projects. The latter contains some rudimentary support for serialization to `*.proto`.

**Comment by blackgnezdo** [comment]
Are you asking for "un-parsing" back into .proto? Considering that we delegate parsing to protoc, I'd say there's no reason to do un-parsing in Haskell.

**Comment by joshsh** [comment]
There is for me. I need to programmatically create Protobuf definitions and write them out to files. It allows us to define corresponding types for use in Protobuf and Thrift, in parallel, from a single source. Who says only humans are allowed to create *.proto files?

**Comment by blackgnezdo** [comment]
I agree such code could be useful. I'm just saying proto-lens would be an unusual place to expect it to exist. The main protocol buffers codebase is a much more likely home.

**Comment by joshsh** [comment]
Can you humor a Haskell newbie and point me to an example for parsing a *proto file to `FileDescriptorProto`? I will add a writer / "un-parser" myself if I can test it with a round-trip from *proto and back.

**Comment by judah** [comment]
@joshsh here's an example that parses `any.proto` into a FileDescriptorProto, saving it in a file, and then uses it by printing the file to stdout:

```
$ protoc google/protobuf/any.proto --descriptor_set_out=file.pb
$ protoc --decode_raw < file.pb

1 {
  1: "google/protobuf/any.proto"
  2: "google.protobuf"
  4 {
    1: "Any"
    2 {
      1: "type_url"
      3: 1
      4: 1
      5: 9
...
```

**Comment by joshsh** [comment]
Thanks @judah, but that is command-line `protoc`; I would like to know how to read in `FileDescriptorProto` and manipulate it in Haskell.

I have coded a solution using [proto3-suite](https://github.com/awakesecurity/proto3-suite) which I may contribute back to that project (but I was leaning away from proto3-suite because of a lot of dependencies my project doesn't need).

**Comment by judah** [comment]
To read from a file, you can use:
```
readDescriptor :: FilePath -> IO (Either String Proto.Google.Protobuf.Descriptor.FileDescriptorProto)
readDescriptor path = Data.ProtoLens.decodeMessage <$> Data.ByteString.readFile path
```

Check out the [tutorial](http://google.github.io/proto-lens/tutorial.html) for more on how to manipulate the resulting proto type.

I'll close this ticket since there doesn't appear to be any remaining actionable requests.
