### ISSUE TITLE
Better support for "oneof" fields

### ISSUE THREAD

**Issue by judah** [google/proto-lens#21]
We currently treat "oneof" fields similar to optional fields.  This is an intended backwards-compatible behavior of the wire encoding, but makes some use cases more awkward.

https://developers.google.com/protocol-buffers/docs/proto#oneof

One possible approach is to store the value as a sum type internally, and provide lenses that return a default value when their case isn't set (as well as "maybe'foo" variants).  Another option (less memory efficient) is to store the fields normally, but make each field's lens clear out all the other fields when it's being set.

**Comment by gseitz** [comment]
@judah I spent some time over the weekend to implement the sum-type approach. Do you want me to open a pull request already, or do you want to look at the commit first?

**Comment by judah** [comment]
Sure, thanks for taking a look at this!  Please open a PR and we can discuss it further there.
