### ISSUE TITLE
Add a build job for `cabal new-build`

### ISSUE THREAD

**Issue by judah** [google/proto-lens#212]
We should add a build job to our Travis config that confirms `cabal new-build` works.

TODO:
- [ ] Add a separate build job that tests new-build in CI.  This probably requires adding `build-tool-depends` to `proto-lens-protobuf-types`, `proto-lens-combinators` and `proto-lens-tests`.
- [ ] Document that the `build-tool-depends` attribute is required for `cabal new-build`.

**Comment by hvr** [comment]
Fyi, I've noticed

- https://matrix.hackage.haskell.org/package/proto-lens-protobuf-types
- https://matrix.hackage.haskell.org/package/proto-lens-combinators

See also https://github.com/google/proto-lens/issues/110#issuecomment-318984283

**Comment by judah** [comment]
For consistency, we should probably recommend using `build-tool-depends` for Stack as well as Cabal.

**Comment by judah** [comment]
Fixed by #356.
