### ISSUE TITLE
tutorial: minor correction - defMessage vs def

### ISSUE THREAD

**Issue by awalterschulze** [google/proto-lens#233]
I see that `def` is imported, but `defMessage` is used.
I assume `defMessage` should be `def`.

```haskell
import Data.ProtoLens (def, showMessage)
import Lens.Micro

person :: P.Person
person =
  defMessage
      & P.name      .~ "Fintan"
      & P.age       .~ 24
      & P.addresses .~ [address]
```

This happens 4 times in the person tutorial
https://github.com/google/proto-lens/tree/master/proto-lens-tutorial/person

And in https://github.com/google/proto-lens/tree/master/proto-lens-tutorial/person#building-a-message `def` is not imported

**Comment by judah** [comment]
Thanks for the correction!  The tutorials intentionally use `defMessage`, which was added in `proto-lens >= 0.4`: https://github.com/google/proto-lens/wiki/Migration-Guide#proto-construction
I'll send a PR to make the tutorial more consistent.

**Comment by awalterschulze** [comment]
Ok, but then shouldn't it be?

```haskell
import Data.ProtoLens (defMessage, showMessage)
```

**Comment by awalterschulze** [comment]
Ah I see it is done in the PR, thanks :)

**Comment by awalterschulze** [comment]
Thank you :)
