### ISSUE TITLE
Add a benchmark for endoding/decoding

### ISSUE THREAD

**Issue by judah** [google/proto-lens#24]
We should have a benchmark for encoding to/from the wire format, to make sure that our reflection and abstraction in the parser doesn't cause a significant slowdown compared to other Haskell code, and to give us more confidence when refactoring.  (So far, we haven't done any performance tuning of the code.)

One arbitrary data point: decoding a 1MB proto took ~60ms on my desktop, and decoding followed by encoding (which includes forcing all the fields) took ~230ms.  (The code was compiled with -O2.)

We should probably also benchmark the text format, though that's usually less performance-critical.

**Comment by agrue** [comment]
I am working on a set of `criterion` benchmarks.

**Comment by agrue** [comment]
Some updates... adding `criterion` benchmarks was quite simple. So I'm currently trying to figure out what a reasonable initial set of benchmarks looks like. The only thing remotely like a "standard benchmark" I could find was here: https://github.com/google/protobuf/tree/master/benchmarks. But I'm not sure we benefit much from imitating it; it looks like a raw speed test for a single large, heterogeneous proto. It seems more interesting to me to have a larger number of small, focused test cases to help uncover pathological cases (at least right now, with our largely unoptimized code).

So for the initial PR I guess I'll just come up with a small set of test cases that make sense to me. If anyone disagrees with the above or has any requests for specific benchmarks, please respond here. :)

**Comment by judah** [comment]
That plan sounds great; thanks for taking this on!

Eventually we should test the effect of proto-lens putting all fields in a single, immutable, flat Haskell record.  For large protos my guess is it's significantly less efficient (in particular, for decoding) than languages which can do updates by mutating a single field.  The standard benchmark might help us examine that use case.

**Comment by judah** [comment]
Closing since the current set of benchmarks has proven useful so far.  If we run into any particular bottlenecks in the future, we can add more specific benchmarks as needed.
