### ISSUE TITLE
Generated EqPred ~ constraints may be slow

### ISSUE THREAD

**Issue by nh2** [google/proto-lens#250]
I noticed proto-lens generate code like this:

```haskell
instance (a ~ Prelude.Bool, b ~ Prelude.Bool, Prelude.Functor f) =>
         Lens.Labels.HasLens "myfield" f MyRequest
           MyRequest
           a
           b
         where
        lensOf _
          = (Prelude..)
              (Lens.Family2.Unchecked.lens _MyRequest'myfield
                 (\ x__ y__ -> x__{_MyRequest'myfield = y__}))
              Prelude.id
```

Doing `a ~ Bool` instead of inlining `Bool` where `a` is used _may_ destroy performance, see https://ghc.haskell.org/trac/ghc/ticket/14941.

I thought you might find this interesting / want to track that.

**Comment by judah** [comment]
Thank you for the suggestion!  Luckily, in proto-lens-0.4.0.0 (PR #208) we simplified the HasLens class and no longer generate `~` constraints.  For example:
http://hackage.haskell.org/package/proto-lens-0.4.0.1/docs/src/Proto.Google.Protobuf.Descriptor.html#line-80
