### ISSUE TITLE
Error in setting up with stack --nix

### ISSUE THREAD

**Issue by wpoosanguansit** [google/proto-lens#313]
Hi,

I did follow the tutorial and have the packages import following the package.yml shown.  However, I am still having a compile error:

    /run/user/1000/stack-dd502342aef372ea/proto-lens-protoc-0.3.1.2/app/protoc-gen-haskell.hs:17:39: error:
        Module `Data.ProtoLens' does not export `def'
       |
    17 | import Data.ProtoLens (decodeMessage, def, encodeMessage)
       | 

Is there any extra step to expose def function from Data.ProtoLens?  Thanks for your help.

**Comment by judah** [comment]
It sounds like you're using incompatible versions of the packages.  We renamed "def" to "defMessage" in proto-lens-0.4 and proto-lens-protoc-0.4, but it looks from your command-line like you're using proto-lens-protoc-0.3.  Maybe try fixing the package versions in stack.yaml?

**Comment by wpoosanguansit** [comment]
Thanks.  Let me try that.

**Comment by wpoosanguansit** [comment]
Hi,

I did fix the version for protoc to 0.4.0.0 and I have got over the error.  However, I am running into these error:

setup: can't find source for Proto/Person in .,
.stack-work/dist/x86_64-linux-nix/Cabal-2.2.0.1/build/autogen,
.stack-work/dist/x86_64-linux-nix/Cabal-2.2.0.1/build/global-autogen

I do have this in the setup:

import Data.ProtoLens.Setup

main = defaultMainGeneratingProtos "Proto"

And src/ProtobufTest/Proto/*.proto in my extra-source-files section.  Any extra step needed?  Thanks for your help.

**Comment by wpoosanguansit** [comment]
Hi,

I tried to create a project from the tutorial and I am still running into the issues below.  I have attached the sample project below.  Thanks for any help.

    Perhaps you meant       
      Data.ProtoLens.Runtime.Lens.Family2 (from lens-family-1.2.3, reexporting lens-family-1.2.3:Lens.Family2)
    Use -v to see a list of the files searched for.
   |                        
11 | import qualified Data.ProtoLens.Runtime.Lens.Labels.Prism
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
                            
....person/.stack-work/dist/x86_64-linux-nix/Cabal-2.4.0.1/build/autogen/Proto/Person.hs:33:1: error:
    Could not find module ‘Data.ProtoLens.Runtime.Lens.Labels’
    Perhaps you meant       
      Data.ProtoLens.Runtime.Lens.Family2 (from lens-family-1.2.3, reexporting lens-family-1.2.3:Lens.Family2)
      Data.ProtoLens.Runtime.Text.Read (from base-4.12.0.0, reexporting Text.Read)
      Data.ProtoLens.Runtime.Data.Map (from containers-0.6.0.1, reexporting containers-0.6.0.1:Data.Map)
    Use -v to see a list of the files searched for.
   |                        
33 | import qualified Data.ProtoLens.Runtime.Lens.Labels as Lens.Labels
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[person.tar.gz](https://github.com/google/proto-lens/files/2920405/person.tar.gz)

**Comment by judah** [comment]
That error means the component is missing the `proto-lens-runtime` dependency.  For example:
https://github.com/google/proto-lens/blob/master/proto-lens-tutorial/person/package.yaml#L14

**Comment by judah** [comment]
Sorry, I misread the error.  You have a mismatch between the versions of proto-lens-protoc and proto-lens-runtime.   They (and proto-lens) should all be either at 0.4.* or 0.5.*.

You're getting these issues because of having `allow-newer: true` in your `stack.yaml`.  If I remove it, I get:
```
    proto-lens-0.5.0.0 from stack configuration does not match ==0.4.*  (latest
                       matching version is 0.4.0.1)
needed due to person-0.0.0 -> proto-lens-protoc-0.4.0.0
```

**Comment by judah** [comment]
Also, for what it's worth, I was able to get your project building by completely removing your "extra-deps" section and instead letting the Stack resolver choose all the package versions.  (`lts-13` will give you `proto-lens-0.4.*`; `nightly` will give you `proto-lens-0.5.*`.)

**Comment by wpoosanguansit** [comment]
Thanks for your help.
