### ISSUE TITLE
Expand documentation for exceptions in label names

### ISSUE THREAD

**Issue by wigahluk** [google/proto-lens#333]
If a proto has a property named `type`, the generated label will be `#type'` which is hard to discover if you don't know it beforehand.

**Comment by blackgnezdo** [comment]
The full list per @agrue:
https://github.com/google/proto-lens/blob/b5802fcf848ac04386f48cdb079fe8c2710e2d40/proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs#L546
