### ISSUE TITLE
Collision with code generated from Google Protobuf repo

### ISSUE THREAD

**Issue by jpgneves** [google/proto-lens#344]
Hi,

I'm attempting to use `proto-lens` with [rules_haskell](https://github.com/tweag/rules_haskell) to generate a Haskell library for [Open Match](https://github.com/googleforgames/open-match) protobuf definitions, and I'm running into a situation where the `.proto` file depends on `google/protobuf/descriptor.proto`, which means that in my `BUILD.bazel` file I must depend on a `@com_google_protobuf//:descriptor_proto` target so that `protoc` can find the files that are included.

This is a pattern in other repos using Bazel, and you can see an example here: https://github.com/googleapis/googleapis/blob/master/google/api/BUILD.bazel#L12

Example of a file I'm attempting to generate Haskell from: https://github.com/googleforgames/open-match/blob/master/third_party/google/api/annotations.proto#L20

Trying to do so will cause `proto-lens-protoc` to generate a `Proto.Google.Protobuf.Descriptor` module which collides with the one included with `proto-lens` since https://github.com/google/proto-lens/pull/140 .

```
   Ambiguous module name `Proto.Google.Protobuf.Descriptor':
     it was found in multiple packages:
       descriptor-proto proto-lens-0.4.0.1
   |
25 | import qualified Proto.Google.Protobuf.Descriptor
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I haven't been able to find a solution that would make both `protoc` and `proto-lens` happy. Any suggestion would be appreciated.

Thanks!

**Comment by judah** [comment]
Thanks for the report.  This may be better reported in the tweag/rules_haskell repo; they've been using protos so may have run into this in the past.

In Cabal/Stack, the proto-lens library itself provides the relevant .proto files:
https://github.com/google/proto-lens/blob/5e5bec02a4193d0a0d797da3551fc0893adb836e/proto-lens/package.yaml#L27

One idea is for rules_haskell to do a similar approach, it could provide the descriptor.proto and plugin.proto automatically without needing an explicit dependency on `:descriptor_proto`.

However, it's possible that this mismatch indicates an issue with our approach.  I'll think more about whether we could do something differently on our end.

**Comment by jpgneves** [comment]
Thanks for the quick response! I had missed the `data-files` declaration in the YAML. I'll give a poke around rules_haskell and report the issue there if I don't find a decent solution myself.
