### ISSUE TITLE
using with cabal needs build-tool-depends field?

### ISSUE THREAD

**Issue by robinp** [google/proto-lens#345]
When trying to use `cabal new-build`, I get

```

Configuring kythe-proto-0.1.0.0...
==========
Error: couldn't find the executable "proto-lens-protoc" in your $PATH.
    Please file a bug at https://github.com/google/proto-lens/issues .
==========
Missing executable "proto-lens-protoc"
CallStack (from HasCallStack):
  error, called at src/Data/ProtoLens/Setup.hs:416:13 in proto-lens-setup-0.4.0.2-cff939ff992c1a90b53165e5fb18582702d245249d87bc11ac95108b8eae9815:Data.ProtoLens.Setup
```
Adding
```
build-tool-depends:  proto-lens-protoc:proto-lens-protoc >= 0.5
```
to the cabal file seems to solve it. 

Note: oddly stack works without this change, even though I don't have proto-lens-protoc on the path. Maybe it gets picked up during the stack build somehow.

**Comment by judah** [comment]
Apologies, this is a known issue #212.  We need to update the documentation.

stack (and cabal old-style build) work because they install proto-lens-protoc as part of building the package.  It's a bit fragile though.
