### ISSUE TITLE
sudo unzip -o $PROTOC_ZIP -d /usr/local include/*  zsh: no matches found: include/*

### ISSUE THREAD

**Issue by kishansagathiya** [google/proto-lens#346]
![Screenshot from 2019-10-02 19-32-51](https://user-images.githubusercontent.com/10185999/66050840-8baa1c00-e54b-11e9-86ea-16cff0fc6c7c.png)

second last line in the linux installation doesn't work.
this leads to import problems such as
```
✗ protoc --go_out=. types.proto
google/protobuf/timestamp.proto: File not found.
types.proto: Import "google/protobuf/timestamp.proto" was not found or had errors.
types.proto:30:3: "Timestamp" is not defined.
```

My guess is this why there are many questions online about import errors which magically resolve on reinstalling protoc.

**Comment by judah** [comment]
Thanks for the report!  It looks like this was caused by a difference in behavior between bash and zsh.  I've opened a PR to fix this.
