### ISSUE TITLE
package syntax support

### ISSUE THREAD

**Issue by tim2CF** [google/proto-lens#350]
If I have multiple `.proto` files which refer each other with native [package](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#package) protobuf expressions then Haskell auto-generated files can not be compiled, because `proto-lens` ignores `package` expressions. Looks like it trying to use directory structure and file names instead. Is it bug or feature? For me looks like a bug because `package` expressions are part of protobuf standard.

**Comment by judah** [comment]
Can you give a more specific example?  proto-lens does use the package of imported modules to resolve references to names.  For example:
https://github.com/google/proto-lens/blob/6e8b73d6a29556cc2e3550a9235d7b7df42b7a20/proto-lens-tests/tests/imports_dep.proto#L12

**Comment by judah** [comment]
Closing due to lack of response; please feel free to reopen with a more specific reproducing example.

**Comment by tim2CF** [comment]
It resolves it by file name, but not by package name 
For example 
```
package Foo.Bar;
```
will not be resolved in expression in other file
```
import "Foo.Bar";
```
because `proto-lens` adds some prefix to module name (will expect something like `Proto.MySubmodule.FooBar`)

**Comment by tim2CF** [comment]
@judah Another example. There are 3 files:

./proto/my_app/global/currency_code.proto
```
syntax = "proto3";
package MyApp.Global;

enum CurrencyCode {
  XXX = 0; 
  BTC = 1; 
  EUR = 2;
  USD = 3;
}

message CurrencyCodeValue {
  CurrencyCode value = 1;
}
```

./proto/my_app/global/decimal.proto
```
syntax = "proto3";
package MyApp.Global;

message Decimal {
  bool negative = 1;
  uint64 coef   = 2;
  int32 exp     = 3;
}
```

./proto/my_app/global/money.proto
```
syntax = "proto3";
package MyApp.Global;

message Money {
  Decimal amount                  = 1;
  CurrencyCodeValue currency_code = 2;
}
```

Which is valid for other protobuf compilers, but proto-lens gives an error

```
"MyApp.Global.Decimal" seems to be defined in "my_app/global/decimal.proto", which is not imported by "my_app/global/money.proto".  To use it here, please add the necessary import.
```

**Comment by judah** [comment]
The error message tells you how to fix it: you need to add explicit `import` statements to use definitions from other proto files:
https://developers.google.com/protocol-buffers/docs/proto3#importing-definitions

Specifically, add to `money.proto`:

```
import "my_app/global/decimal.proto";
import "my_app/global/currency_code.proto";
```

Importing by filename is part of the file specification, and as far as I'm aware is the same for other language implementations.  (In fact, that error isn't coming directly from proto-lens, but rather from the standard protocol compiler (`protoc`) binary that it uses.

**Comment by tim2CF** [comment]
Thanks!
