### ISSUE TITLE
Can't find protoc in PATH when using nix

### ISSUE THREAD

**Issue by bbarker** [google/proto-lens#371]
Not sure why this would matter, but here's the error and evidence that `protoc` is on the PATH:

```
[nix-shell:~/workspace/CIDA/FarmDataServer]$ stack --nix build
Cabal file warning in/home/brandon/workspace/CIDA/FarmDataServer/FarmDataServer.cabal@58:3: Unknown field: "build-tool-depends"
FarmDataServer> configure (lib + internal-lib + exe)
Warning: FarmDataServer.cabal:58:3: Unknown field: "build-tool-depends"
Configuring FarmDataServer-0.1.0.0...
FarmDataServer> build (lib + internal-lib + exe)
==========
Error: couldn't find the executable "protoc" in your $PATH.
    Follow the installation instructions at https://google.github.io/proto-lens/installing-protoc.html .
==========
Missing executable "protoc"
CallStack (from HasCallStack):
  error, called at src/Data/ProtoLens/Setup.hs:416:13 in proto-lens-setup-0.4.0.2-K3h1t3Y3qTCJGacEzRl15J:Data.ProtoLens.Setup

--  While building package FarmDataServer-0.1.0.0 using:
      /home/brandon/workspace/CIDA/FarmDataServer/.stack-work/dist/x86_64-linux-nix/Cabal-2.4.0.1/setup/setup --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-2.4.0.1 build lib:FarmDataServer lib:prelude exe:FarmDataServer.exe exe:tests.exe --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1

[nix-shell:~/workspace/CIDA/FarmDataServer]$ which protoc 
/nix/store/k0qs3lj5dvc8xc57zz8czpdkk4ggqlvq-protobuf-3.9.1/bin/protoc


[nix-shell:~/workspace/CIDA/FarmDataServer]$ protoc --version
libprotoc 3.9.1

```

Also, any ideas for workarounds for now? Thanks!

**Comment by judah** [comment]
I believe Stack starts a separate hermetic Nix environment for your project, which by default won't have your regular PATH.  You probably need to add a package containing `protoc` to the `nix:` section, as described here:
https://docs.haskellstack.org/en/stable/nix_integration/

To test this, I believe you can do:

```
stack --nix -- which protoc
```

to see whether Stack's nix environment contains the `protoc` binary.

Please let us know whether that resolves the issue for you.

**Comment by bbarker** [comment]
I had forgotten that stack created a pure environment; yes, this method works. Specifically I had a stack nix expression file as described [here](https://docs.haskellstack.org/en/stable/nix_integration/#using-a-custom-shellnix-file), and adding `protobuf` to that file solved the issue.
