### ISSUE TITLE
In proto3, repeated fields of scalar numeric types use packed encoding by default.

### ISSUE THREAD

**Issue by pippijn** [google/proto-lens#38]
See https://developers.google.com/protocol-buffers/docs/proto3#specifying-field-rules. proto-lens generated code does not implement this correctly. Trying to decode repeated fields of scalar numeric types (like int32 and float) results in a message like "Field 1 expects wire type 0 but found 2", because packed repeated fields are wire type 2 (see https://developers.google.com/protocol-buffers/docs/encoding#structure).

**Comment by iphydf** [comment]
Also, "Protocol buffer parsers must be able to parse repeated fields that were compiled as packed as if they were not packed, and vice versa. This permits adding [packed=true] to existing fields in a forward- and backward-compatible way."

**Comment by judah** [comment]
Fixed by #64.
