### ISSUE TITLE
Field presence support per proto3 change

### ISSUE THREAD

**Issue by blackgnezdo** [google/proto-lens#380]
Should we do something about newly allowed `optional` fields in proto3?
https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md

**Comment by judah** [comment]
Oh, interesting, I hadn't seen that. Yeah, we probably should eventually, although from the docs it seems pretty experimental so far. It's guarded by the `--experimental_allow_proto3_optional` flag to `protoc`, and only supported in version 3.12 which doesn't seem to have been released yet.

We do already have support for optional scalars in proto2 fields, so this probably just means generating `maybe'*` lenses for these fields, as well as switching corresponding `Message.FieldDescriptor` from the "required" to "optional" case. (And also updating some documentation.)

The open question I have is how this all gets signaled in the `FieldDescriptorProto` that our plugin uses to make these decisions. Our current logic for parsing that information is here:
https://github.com/google/proto-lens/blob/f49f71b6427f461d8caa2f38a7d6965f46ad1f85/proto-lens-protoc/app/Data/ProtoLens/Compiler/Definitions.hs#L427

**Comment by judah** [comment]
To clarify: it's possible we *only* need to change that code block, and then everything will "just work". But I'd need to understand the implications of this change on `DescriptorProto` to know for sure.

**Comment by judah** [comment]
These docs explain the situation from an implementor's perspective:
https://github.com/protocolbuffers/protobuf/blob/7eddac7877b6983cdb23a082dcbe63efe3403b95/docs/implementing_proto3_presence.md

**Comment by jinwoo** [comment]
@judah Any chance you looked into this? There seems to be demands within Google. No pressure :)

**Comment by judah** [comment]
@jinwoo I probably won't have bandwidth to work on this in the short term, but I'm happy to help advise/review anyone who wants to tackle it. My gut instinct is it wouldn't be a big change, mainly requires digging into the doc I linked above and thinking about how the API should change.

**Comment by jinwoo** [comment]
@judah No worries. I wish I could take a look but I don't have the bandwidth for this either at the moment (Sadly we don't have full-time Haskell engineers anymore).
