### ISSUE TITLE
Support GHC 8.10

### ISSUE THREAD

**Issue by blackgnezdo** [google/proto-lens#381]
I'd like to get some help with supporting this new release. Some items that likely require attention:

  * Getting a working build plan
  * Adapting to GHC internal API changes (if any)

**Comment by jinwoo** [comment]
This at least requires ghc-source-gen also support 8.10.

**Comment by yaitskov** [comment]
github CI
```
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.0.2.0 supports
'ghc' version < 8.10): /opt/ghc/8.10.1/bin/ghc is version 8.10.1
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: megaexample-0.4.2 (user goal)
[__1] trying: base-4.14.0.0/installed-4.1... (dependency of megaexample)
[__2] trying: opentelemetry-extra-0.4.2 (user goal)
[__3] next goal: proto-lens (dependency of opentelemetry-extra)
[__3] rejecting: proto-lens-0.6.0.0 (conflict:
base==4.14.0.0/installed-4.1..., proto-lens => base>=4.10 && <4.14)
```

**Comment by yaitskov** [comment]
@jinwoo , [ghc-source-gen has been fixed](https://github.com/google/ghc-source-gen/issues/65).

**Comment by jinwoo** [comment]
@yaitskov Yeah I know (I'm the one who reviewed that change 😄 ). I just didn't have a chance to work on this. Let me do this soon unless someone else is already working.

**Comment by jinwoo** [comment]
I'm struggling with the `cassava` package. It fails to build with errors like below. I tried adding `text-short-0.1.3` to the new `stack-8.10.yaml` file but it didn't work.

@judah Any magic you know of?

```
cassava                  > /tmp/stack-031cc73279663f7f/cassava-0.5.2.0/src/Data/Csv/Conversion.hs:26:3: error:
cassava                  >      error: #error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-
4` flag-logic in the .cabal file wasn't elided.                                      
cassava                  >        26 | # error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10
-4` flag-logic in the .cabal file wasn't elided.                                       
cassava                  >           |   ^~~~~                                
cassava                  >    |                                                      
cassava                  > 26 | # error **INVARIANT BROKEN** Detected invalid combination of `text-short` and `bytestring` versions. Please verify the `pre-bytestring-0.10-4` fla
g-logic in the .cabal file wasn't elided.                                                
cassava                  >    |   ^                                            
cassava                  >                                                            
cassava                  > /tmp/stack-031cc73279663f7f/cassava-0.5.2.0/src/Data/Csv/Conversion.hs:100:0: error:
cassava                  >      warning: "MIN_VERSION_text_short" is not defined, evaluates to 0 [-Wundef]
cassava                  >       100 | #if MIN_VERSION_text_short(0,1,0)
cassava                  >           |                                 
...
```

**Comment by jinwoo** [comment]
https://github.com/haskell-hvr/cassava/issues/177 seems to suggest that the problem is `allow-newer`. But we need `allow-newer` for GHC 8.10 until Stackage properly supports GHC 8.10. I'm not sure how to work around this.

**Comment by judah** [comment]
For ghc-source-gen, I avoided `allow-newer` by creating a new YAML file for 8.10 with explicit versions for all the dependencies. Stack actually helped recommend some extra-deps automatically. (I think that's because I used a custom resolver.)
https://github.com/google/ghc-source-gen/blob/83c3ccf080985670bb7859325e1f5da45b2b5d72/stack-8.10.yaml#L24

**Comment by judah** [comment]
Alternately you might be able to fix it by specifying a small number of other packages explicitly in addition to `text-short`: namely, those deps of `cassava` that are causing problems, for example, `bytestring`.

**Comment by jinwoo** [comment]
Well `ghc-source-gen` still has `allow-newer`: https://github.com/google/ghc-source-gen/blob/83c3ccf080985670bb7859325e1f5da45b2b5d72/stack-8.10.yaml#L45

I tried adding various packages as suggested by stack but `cassava` didn't work even when I specified the matching `text-short` and `bytestring` versions. I'll try again tomorrow.

**Comment by judah** [comment]
Oh, oops, I didn't realize I left it in. It turns out it's not needed, so I sent a PR to remove it: google/ghc-source-gen#72

One other thing you could try is to set Cassava's flags explicitly in the `stack.yaml`:
https://docs.haskellstack.org/en/stable/yaml_configuration/#flags

It looks like they set it explicitly in the LTS configuration:
https://github.com/commercialhaskell/lts-haskell/blob/8b942a5a7e93708e75ddf955184913a1ee6a68ab/lts-14.9.yaml#L12553

**Comment by jinwoo** [comment]
Oh, I saw that flag (`bytestring--lt-0_10_4`) yesterday but didn't think of using that. I didn't know Stackage was using it. I'll try that.

**Comment by jinwoo** [comment]
That flag was the trick!

**Comment by jinwoo** [comment]
@judah I'm seeing a test error only with GHC 8.10 like below. Any idea?

```
proto-lens-tests         > /usr/local/google/home/jinwoo/src/proto-lens/proto-lens-tests/tests/enum_test.hs:161:9: error: [-Woverlapping-patterns, -Werror=overlapping-patterns]
proto-lens-tests         >     Pattern match is redundant
proto-lens-tests         >     In a case alternative: Alias1 -> ...
proto-lens-tests         >     |
proto-lens-tests         > 161 |         Alias1 -> Alias1
proto-lens-tests         >     |         ^^^^^^^^^^^^^^^^
proto-lens-tests         >    
proto-lens-tests         > /usr/local/google/home/jinwoo/src/proto-lens/proto-lens-tests/tests/enum_test.hs:163:9: error: [-Woverlapping-patterns, -Werror=overlapping-patterns]
proto-lens-tests         >     Pattern match is redundant
proto-lens-tests         >     In a case alternative: Alias3 -> ...
proto-lens-tests         >     |
proto-lens-tests         > 163 |         Alias3 -> Alias3
proto-lens-tests         >     |         ^^^^^^^^^^^^^^^^
proto-lens-tests         >    
```

**Comment by jinwoo** [comment]
Probably something changed between 8.6 and 8.10 regarding pattern matching or pattern synonym. I'll remove those cases with GHC 8.10.

**Comment by yaitskov** [comment]
I am still experiencing the issue. The latest version on Hackage is not changed yet.
It is 0.6.0.0.
I tried to upgrade resolver to from 15.13 to 15.15
allow-newer: true
https://github.com/ethercrow/opentelemetry-haskell/pull/23

```
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.0.2.0 supports
'ghc' version < 8.10): /opt/ghc/8.10.1/bin/ghc is version 8.10.1
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: megaexample-0.4.2 (user goal)
[__1] trying: base-4.14.0.0/installed-4.1... (dependency of megaexample)
[__2] trying: opentelemetry-extra-0.4.2 (user goal)
[__3] next goal: proto-lens (dependency of opentelemetry-extra)
[__3] rejecting: proto-lens-0.6.0.0 (conflict:
base==4.14.0.0/installed-4.1..., proto-lens => base>=4.10 && <4.14)
[__3] rejecting: proto-lens-0.5.1.0, proto-lens-0.5.0.1, proto-lens-0.5.0.0,
proto-lens-0.4.0.1 (conflict: base==4.14.0.0/installed-4.1..., proto-lens =>

```

Is there any extra workaround I missed?

**Comment by jinwoo** [comment]
@yaitskov Sorry we didn't publish the new versions yet. We're having some problems at the moment. Hopefully we'll be able to publish soon.

**Comment by jinwoo** [comment]
Now the new version has been published.
