### ISSUE TITLE
proto-lens-protobuf-types won't compile.

### ISSUE THREAD

**Issue by skynet1** [google/proto-lens#395]
proto-lens-protobuf-types won't compile when I try to install it with cabal. 
It gives the error in the attached file.
[error.txt](https://github.com/google/proto-lens/files/4820519/error.txt)
cabal version is 3.2.0.0 and ghc version is 8.6.5 .

**Comment by judah** [comment]
It looks like you're using proto-lens-protobuf-types v0.5.0.0, which didn't work as well with Cabal v3. In particular: #345; the build-tool-depends flag, which is needed to properly resolve the right version of proto-lens-protoc, wasn't added until v0.6.0.0.)

Can you try using version 0.7.0.0 of the package instead?

@blackgnezdo FYI the error was encountered with tensorflow-proto; we should probably update that package to the newer versions of proto-lens packages.

**Comment by skynet1** [comment]
I just tried to compile it from the source repo using the instructions from the README and it compiles now and drops me into ghci.

**Comment by judah** [comment]
Thanks for the update! Glad to hear it's working for you.
