### ISSUE TITLE
Find a path forward for CI

### ISSUE THREAD

**Issue by blackgnezdo** [google/proto-lens#405]
Per Google policy we can't [migrate to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) as it requires additional [write access to the repo](https://docs.travis-ci.com/user/github-oauth-scopes/).

Thus we should look at some alternatives promptly.

Some possible alternatives we could explore:
 * Cloud Build
 * Kokoro
 * GitHub Actions
 * CircleCI
 * AppVeyor

Opinions? Volunteers?

**Comment by blackgnezdo** [comment]
I have an unfinished attempt to use Actions in https://github.com/blackgnezdo/proto-lens/pull/1

**Comment by awpr** [comment]
FYI I spent last weekend setting up https://github.com/google/hs-portray/actions/runs/1252211007 -- it looks like proto-lens doesn't use Stack, but perhaps either you could add a stack build and use it as-is, or use it as a basis for a cabal one.
