### ISSUE TITLE
google/protobuf/struct.proto not included in protobuf types

### ISSUE THREAD

**Issue by tochicool** [google/proto-lens#437]
The struct type from [`google/protobuf/struct.proto`](https://github.com/protocolbuffers/protobuf/blob/2514f0bd7da7e2af1bed4c5d1b84f031c4d12c10/src/google/protobuf/struct.proto) is used in a lot of common schemas but missing from generated modules of the `proto-lens-protobuf-types` package.

**Comment by 4eUeP** [comment]
@blackgnezdo Hi, is there any plan to publish a new `proto-lens-protobuf-types` package to hackage? I find the latest version `0.7.1.1` doesn't include the `Struct`

**Comment by blackgnezdo** [comment]
I published [0.7.1.2](https://hackage.haskell.org/package/proto-lens-protobuf-types-0.7.1.2).
