### ISSUE TITLE
Support GHC 9.4

### ISSUE THREAD

**Issue by jchia** [google/proto-lens#447]
The latest ghc is 9.4.4 but the upper bound is <9.3.
The latest base is 4.17.0.0 but the upper bound is <4.17.

Consequently, many packages in this project are not in stackage nightly.

**Comment by blackgnezdo** [comment]
Yeah, it would be good if somebody contributed a new entry to the build matrix. It's also likely a good time to drop ghc-8.8 now.

**Comment by blackgnezdo** [comment]
I started on this in #448 if somebody needs inspiration.

**Comment by ysangkok** [comment]
There is now a build for ghc 9.6, but only for some packages. So if you just use `proto-lens` and `proto-lens-runtime` for example, you can upgrade to GHC 9.4 or 9.6. The code generation needs changes to work on these new versions.

**Comment by k355l3r-5yndr0m3** [comment]
Ghc 9.8.1 has recently been released, and the latest version of base 4.19. But proto-lens currently is still stuck at 4.16, will newer versions be supported in the near future?

**Comment by ysangkok** [comment]
@k355l3r-5yndr0m3 Where are you looking? It varies from package to package as not all of them need source generation. For `proto-lens` itself, base-4.18 (GHC 9.6) is supported, as you can see in [the cabal file](https://hackage.haskell.org/package/proto-lens-0.7.1.3/src/proto-lens.cabal). We could probably update the core packages to GHC 9.8, try sending a PR with CI support and we can see whether it works.

**Comment by ysangkok** [comment]
@k355l3r-5yndr0m3 Are you sure you need `proto-lens-setup`? You can generate using an older GHC and then compile the generated source using a newer GHC. Or you could try using `proto-lens-setup` with bumped bounds.

**Comment by k355l3r-5yndr0m3** [comment]
That would probably work. Although it would be tedious expectantly if the protocol buffer files change frequently.

**Comment by ysangkok** [comment]
I submitted 

* https://github.com/google/proto-lens/pull/456

which would address this issue. Please review.

**Comment by blackgnezdo** [comment]
Support for up to 9.6 is out on Hackage.
