### ISSUE TITLE
Compilation hangs after some `default-extensions` added.

### ISSUE THREAD

**Issue by Qiu233** [google/proto-lens#452]
After I added these two language extensions to `default-extensions` section of `package.yaml`
```yaml
- NoFieldSelectors
- DuplicateRecordFields
```
Command `stack build` hangs long and task manager shows the process `vmmem` takes more than 50% of CPU, which indicates the compiler is doing some CPU-bound work.
Not sure if it's going to complete or crash, as I terminated it before cpu temperature gets too high.

**Comment by blackgnezdo** [comment]
I don't know how to reproduce this. Wanna try pushing a branch with the exact state of the code which triggers the behavior you observe? I'm closing this report until such a time.
