### ISSUE TITLE
Any way to generate protobuf schema from haskell types?

### ISSUE THREAD

**Issue by AlexeyPirogov** [google/proto-lens#462]
Hi,

Is there a way to generate protobuf schemas from haskell types?

**Comment by blackgnezdo** [comment]
That wouldn't be a use case for `proto-lens`. A quick perusal of hackage suggests that https://hackage.haskell.org/package/proto3-suite is closer to what you have in mind.

**Comment by AlexeyPirogov** [comment]
Thank you, @blackgnezdo .
