### ISSUE TITLE
Please issue new Hackage release of proto-lens-protobuf-types

### ISSUE THREAD

**Issue by domMayhew** [google/proto-lens#463]
I am publishing a library that depends on the additional support for well-known types provided by #460.

Please publish a new version to Hackage so my library can depend on it.

Thanks!

**Comment by blackgnezdo** [comment]
https://hackage.haskell.org/package/proto-lens-protobuf-types-0.7.2.1 is out

**Comment by domMayhew** [comment]
Thanks!
