### ISSUE TITLE
bump or relax version constraint on data-default-class?

### ISSUE THREAD

**Issue by mmaz** [google/proto-lens#51]
Would it be possible to bump the constraint on `data-default-class == 0.0.*` to `data-default-class == 0.1.*` or to relax the constraint? ([Stackage LTS-7.2](https://www.stackage.org/lts-7.2) is pinned to [`data-default-class-0.1.2.0`](https://www.stackage.org/lts-7.2/package/data-default-class-0.1.2.0) for example). Thanks!

**Comment by blackgnezdo** [comment]
I'll take a look Monday if nobody else does before then.

**Comment by blackgnezdo** [comment]
Released on Hackage now.
