### ISSUE TITLE
Factor Data.ProtoLens.Compiler.Combinators into a separate library

### ISSUE THREAD

**Issue by isovector** [google/proto-lens#57]
The `Data.ProtoLens.Compiler.Combinators` module has some combinators for making working with TH much easier. It'd be fantastic if it was moved to a separate library where it could be more widely adopted.

**Comment by judah** [comment]
Just to clarify, those combinators are for the haskell-src-exts ADT, not TemplateHaskell (which it sounds like you were referring to).

But regardless, it does sounds reasonable to split these combinators out into a separate library.

**Comment by judah** [comment]
This will be done as part of #323, by us migrating to the `ghc-source-gen` package.
