### ISSUE TITLE
Please upload the packages which are updated for ghc-8.2.1 to the hackage

### ISSUE THREAD

**Issue by Qinka** [google/proto-lens#97]
Please upload the packages which are updated for ghc-8.2.1 to the hackage.
These packages (on the hackage) are still not able to work with ghc-8.2.1 because of depend `base (>=4.8 && <4.10)` .

**Comment by judah** [comment]
New versions of all the packages, which are compatible with `ghc-8.2.1`, have now been uploaded to Hackage.
